import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { fixture } from './storage.mjs';
const output=await build({entryPoints:['src/api/client.ts'],bundle:true,write:false,format:'esm',platform:'node',define:{'import.meta.env':'{}'}});
const makeApi=async(n)=> (await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text+`\n// ${n}`).toString('base64'))).api;
const store=new Map([['fam_exp_api_url','https://mock.invalid']]);
global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const records=Array.from({length:240},(_,i)=>({id:'id'+i,date:i<120?'2026-09-12':'2025-01-01',amount:1000,type:'expense',category_id:'food',member_id:'wife',created_at:'2026-09-12T02:13:00Z',updated_at:'2026-09-12T02:13:00Z',deleted:false}));
const f=fixture(records);f.context.migrateToYearlyStorage();
const calls=[];let legacy=false;
global.fetch=async(_url,opts)=>{
 const {action,payload}=JSON.parse(opts.body);calls.push(action);
 let body;
 if(legacy&&action==='storageStatus')body={ok:false,error:{code:'INVALID_ACTION',message:'Not supported'}};
 else if(action==='getCategories')body={ok:true,data:f.context.readNamed_('Categories')};
 else if(action==='getBudgets')body={ok:true,data:f.context.readNamed_('Budgets')};
 else body={ok:true,data:f.api(action,payload)};
 return {ok:true,json:async()=>body};
};
const api=await makeApi('modern');
let r=await api.getReportBundle(2026,9);
assert.equal(r.summary.total_expense,120000);assert.equal(r.years.length,2);
assert.deepEqual(calls,['storageStatus','getReportBundle']);
f.metrics.reads=[];calls.length=0;
await api.getReportBundle(2026,10);
assert.deepEqual(calls,['getReportBundle']);assert.equal(f.metrics.reads.filter(n=>n.startsWith('Transactions')).length,0);
const page=await api.getTransactionPage({from:'2026-09-01',through:'2026-09-30',limit:100});assert.equal(page.items.length,100);assert.ok(page.next_cursor);
const page2=await api.getTransactionPage({from:'2026-09-01',through:'2026-09-30',cursor:page.next_cursor});assert.equal(page2.items.length,20);
const searched=await api.getTransactionPage({search:'Ăn uống',from:'2025-01-01',through:'2025-01-31'});assert.equal(searched.items.length,100);
legacy=true;calls.length=0;const older=await makeApi('legacy');r=await older.getReportBundle(2026,9);assert.equal(r.summary.total_expense,120000);assert.equal(calls.filter(a=>a==='getTransactions').length,1);assert.equal(calls.includes('getDashboardSummary'),false);
store.delete('fam_exp_api_url');store.set('fam_exp_transactions',JSON.stringify(records));const offline=await makeApi('offline');assert.equal((await offline.getReportBundle(2026,9)).summary.total_expense,120000);assert.equal((await offline.getTransactionPage({from:'2025-01-01',through:'2025-01-31'})).items.length,100);
console.log('Client integration passed: modern request count, legacy one-scan fallback, offline filtering, pagination.');
