import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fixture} from './storage.mjs';
const compiled=await build({entryPoints:['src/api/client.ts'],bundle:true,write:false,format:'esm',platform:'node',define:{'import.meta.env':'{}'}});
const store=new Map([['fam_exp_api_url','https://mock.invalid'],['family_auth_session','husband']]);
global.localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const {api}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const records=Array.from({length:150},(_,i)=>({id:'id'+i,date:'2026-09-12',type:'expense',amount:1000,member_id:i%2?'wife':'husband',category_id:'food',note:'Test',created_at:'2026-09-12T02:00:00Z',updated_at:'2026-09-12T02:00:00Z',deleted:false}));
const server=fixture(records);server.context.migrateToYearlyStorage();
const normal=async(_url,opts)=>{const {action,payload}=JSON.parse(opts.body);return {ok:true,json:async()=>({ok:true,data:action==='getCategories'?server.context.readNamed_('Categories'):server.api(action,payload)})};};
global.fetch=normal;
const q={from:'2026-09-01',through:'2026-09-30',limit:100};
assert.equal(api.getCachedTransactions(q),null);
const page=await api.getTransactionSnapshot(q);assert.equal(page.data.page.items.length,100);
assert.equal(api.getCachedTransactions(q).data.page.items.length,100);
assert.equal(api.getCachedTransactions({...q,member_id:'wife'}),null);
assert.equal(api.getCachedTransactions({...q,search:'different'}),null);
assert.equal(api.getCachedTransactions({from:'2026-10-01',through:'2026-10-31'}),null);
const second=await api.getTransactionSnapshot({...q,cursor:page.data.page.next_cursor});assert.equal(second.data.page.items.length,50);
assert.equal(api.getCachedTransactions(q).data.page.items.length,100,'Page two never overwrites cached first page');
await api.getReportSnapshot(2026,9);assert.equal(api.getCachedReport(2026,9).data.summary.total_expense,150000);
assert.equal(api.getCachedReport(2026,10),null);
store.set('family_auth_session','wife');assert.equal(api.getCachedTransactions(q),null);assert.equal(api.getCachedReport(2026,9),null);store.set('family_auth_session','husband');
store.set('fam_exp_api_url','https://different.invalid');assert.equal(api.getCachedReport(2026,9),null);store.set('fam_exp_api_url','https://mock.invalid');
global.fetch=async()=>{throw Error('Offline');};await assert.rejects(()=>api.getReportSnapshot(2026,9),/Offline/);assert.equal(api.getCachedReport(2026,9).data.summary.total_expense,150000);
global.fetch=normal;await api.createTransaction({...records[0],amount:2000});assert.equal(api.getCachedTransactions(q),null);assert.equal(api.getCachedReport(2026,9),null);
await api.getTransactionSnapshot({from:'2027-01-01',through:'2027-01-31'});assert.equal(api.getCachedTransactions({from:'2027-01-01',through:'2027-01-31'}).data.page.items.length,0,'Empty month is cacheable');
// A late report response cannot resurrect a snapshot invalidated by a write.
let release;global.fetch=async(_url,opts)=>JSON.parse(opts.body).action==='getReportBundle'?{ok:true,json:()=>new Promise(resolve=>{release=resolve;})}:normal(_url,opts);
const late=api.getReportSnapshot(2026,9);await new Promise(resolve=>setImmediate(resolve));
global.fetch=normal;await api.createTransaction({...records[0],amount:3000});release({ok:true,data:server.api('getReportBundle',{year:2026,month:9})});await assert.rejects(()=>late,/vừa thay đổi/);assert.equal(api.getCachedReport(2026,9),null);
store.set('fam_exp_page_preview_v1','invalid');assert.equal(api.getCachedReport(2026,9),null);
console.log('Page cache tests passed: first-page pagination, filter/month/account isolation, empty months, offline, writes and stale responses.');
